### ISSUE TITLE
Freeze when entering stage 2 of training rave

### ISSUE THREAD

**Issue by elyxlz** [acids-ircam/RAVE#126]
Hello,
I'm having a very weird error.

Whenever the training finishes the warmup stage a couple of iterations go through with the second stage, but then the CLI hangs/freezes. This occurred naturally as well as when I manually changed `warmed_up = True` and restarted training from the checkpoint. This is what it looks like with the latter:

```
python train_rave.py -c default --name proto_v4 --wav /home/elyx/myData/processedData_noAug_v0/out_48000 --preprocessed /home/elyx/proto_v4/rave --sr 48000 --data-size 32 --n-signal 131072 --warmup 1000 --no-latency false --ckpt /home/elyx/RAVE/runs/proto_v4/rave --max-kl 0.1
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at /home/elyx/RAVE/runs/proto_v4/rave/version_2/checkpoints/last.ckpt
/home/elyx/miniconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:342: UserWarning: The dirpath has changed from 'runs/proto_v4/rave/version_2/checkpoints' to 'runs/proto_v4/rave/version_38/checkpoints', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.
  warnings.warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                | Params
------------------------------------------------------
0 | pqmf          | CachedPQMF          | 66.6 K
1 | loudness      | Loudness            | 0
2 | encoder       | Encoder             | 4.8 M
3 | decoder       | Generator           | 12.8 M
4 | discriminator | StackDiscriminators | 16.9 M
------------------------------------------------------
34.6 M    Trainable params
0         Non-trainable params
34.6 M    Total params
138.521   Total estimated model params size (MB)
Restored all states from the checkpoint file at /home/elyx/RAVE/runs/proto_v4/rave/version_2/checkpoints/last.ckpt
Epoch 88:   0%|                                                        | 2/2415 [00:01<-1:59:59, -1306.36it/s, v_num=38]

```

When running with pdb, I manage to get a stack trace when pressing Ctrl+C, instead of nothing happening:

```
Program interrupted. (Use 'cont' to resume).
> /home/elyx/miniconda3/envs/rave/lib/python3.9/selectors.py(419)select()
-> for fd, event in fd_event_list:
(Pdb)
Process Process-29:
Traceback (most recent call last):
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 269, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/multiprocessing/connection.py", line 429, in _poll
    r = wait([self], timeout)
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/multiprocessing/connection.py", line 936, in wait
    ready = selector.select(timeout)
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/selectors.py", line 419, in select
    for fd, event in fd_event_list:
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/selectors.py", line 419, in select
    for fd, event in fd_event_list:
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/elyx/miniconda3/envs/rave/lib/python3.9/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

I am running on WSL2 with an RTX 2080 Ti. Windows 11.

If anyone could help me that would be great!

**Comment by elyxlz** [comment]
Solved it, had to update WSL. WSL had some limitations with CUDA prior to the update.
