### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by Monratus** [acids-ircam/RAVE#127]
Ok so this might not be a big issue, but I can't seem to be able to train RAVE on my computer because of this simple line:
```python
    preprocess = lambda name: simple_audio_preprocess(
        args.SR,
        2 * args.N_SIGNAL,
    )(name).astype(np.float16)
```

All I get is : 
```
Traceback (most recent call last):
  File "..\02_Models\RAVE\train_rave.py", line 99, in <module>
    dataset = SimpleDataset(
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\udls\simple_dataset.py", line 80, in __init__
    self._preprocess()
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\udls\simple_dataset.py", line 120, in _preprocess
    output = self.preprocess_function(wav)
  File "..\02_Models\RAVE\train_rave.py", line 94, in <lambda>
    preprocess = lambda name: simple_audio_preprocess(
AttributeError: 'NoneType' object has no attribute 'astype'
```

I feel a little bit lost here... I also tried to remove the cast to float 16 and ended up with a `No data found !` error. My dataset is comprised of 1 802 .wav stereo files at 44100Hz (15 Gb).  
It's probably a silly problem, but I would really like to test this model!

**Comment by caillonantoine** [comment]
It looks like the model can't find your data. Make sure you haven't spelled the path wrong !
