### ISSUE TITLE
lmdb.Error: C:\Users\Pondsi\AppData\Local\Temp: �ϺЪ��Ŷ������C

### ISSUE THREAD

**Issue by huangtaoyun5** [acids-ircam/RAVE#133]
while trainind the firt call on win11, this **lmdb.Error** comes out, don't know where's the problem, maybe have not enough disk space?
:
(rave) PS C:\Users\Pondsi\RAVE> python train_rave.py -c small --name reel --wav "C:\Users\Pondsi\123" --preprocessed "C:\Users\Pondsi\AppData\Local\Temp" --sr 44100 --data-size 16 --n-signal 60000 --no-latency false --max-kl 0.1
Traceback (most recent call last):
  File "C:\Users\Pondsi\RAVE\train_rave.py", line 99, in <module>
    dataset = SimpleDataset(
  File "D:\miniconda\envs\rave\lib\site-packages\udls\simple_dataset.py", line 66, in __init__
    self.env = SimpleLMDBDataset(out_database_location, map_size)
  File "D:\miniconda\envs\rave\lib\site-packages\udls\base_dataset.py", line 12, in __init__
    self.env = lmdb.open(out_database_location,
lmdb.Error: C:\Users\Pondsi\AppData\Local\Temp: �ϺЪ��Ŷ������C

**Comment by huangtaoyun5** [comment]
indeed, the disk space wasn't enough
