### ISSUE TITLE
lmdb.InvalidParameterError: Invalid argument

### ISSUE THREAD

**Issue by schramm** [acids-ircam/RAVE#150]
When trying to run  train_rave.py:

train_rave.py -c small --name test1 --wav wave_data --preprocessed out_dir --sr 16000 --data
-size 16 --n-signal 65536 --no-latency false --cropped-latent-size 128 --max-kl 0.1

 I am getting the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/python3.10/site-packages/udls/simple_dataset.py", line 66, in __init__
    self.env = SimpleLMDBDataset(out_database_location, map_size)
  File "~/python3.10/site-packages/udls/base_dataset.py", line 12, in __init__
    self.env = lmdb.open(out_database_location,
lmdb.InvalidParameterError: out_dir: Invalid argument

It seems to be related to  --preprocessed argument. Is this just a directory path, or should I pass something else?

**Comment by schramm** [comment]
This is happening in a  MacOS M1 machine without CUDA.  I tested  it on Ubuntu + Cuda and it is working.
