### ISSUE TITLE
rave train error when executed in a conda venv

### ISSUE THREAD

**Issue by jacklion710** [acids-ircam/RAVE#169]
I decided to try and utilize my GPU for training after reading [this](https://github.com/acids-ircam/RAVE/discussions/110) and realizing that my current session was not using my GPU. After setting up the anaconda virtual environment and installing the requirements into it, I preprocessed the data successfully. After that, running the `rave train ...` command returns the following log/errors:

```
(rave_env) C:\Users\Jake>rave train --config v2 --db_path C:/Users/Jake/Desktop/Dataset --name jl-sounds-study
C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
I0131 23:52:01.541437 32128 resource_reader.py:50] system_path_file_exists:v2.gin
E0131 23:52:01.541934 32128 resource_reader.py:55] Path not found: v2.gin
I0131 23:52:01.541934 32128 resource_reader.py:50] system_path_file_exists:C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\rave\v2.gin
E0131 23:52:01.542430 32128 resource_reader.py:55] Path not found: C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\rave\v2.gin
I0131 23:52:01.542927 32128 resource_reader.py:50] system_path_file_exists:configs/v1.gin
E0131 23:52:01.543423 32128 resource_reader.py:55] Path not found: configs/v1.gin
RAVE(
  (pqmf): CachedPQMF(
    (forward_conv): Conv1d(1, 16, kernel_size=(513,), stride=(16,), bias=False)
    (inverse_conv): Conv1d(16, 16, kernel_size=(33,), stride=(1,), bias=False)
  )
  (encoder): VariationalEncoder(
    (encoder): EncoderV2(
      (net): CachedSequential(
        (0): Conv1d(16, 96, kernel_size=(7,), stride=(1,), bias=False)
        (1): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (2): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (3): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (4): LeakyReLU(negative_slope=0.2)
        (5): Conv1d(96, 192, kernel_size=(8,), stride=(4,), bias=False)
        (6): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (7): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (8): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (9): LeakyReLU(negative_slope=0.2)
        (10): Conv1d(192, 384, kernel_size=(8,), stride=(4,), bias=False)
        (11): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (12): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (13): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (14): LeakyReLU(negative_slope=0.2)
        (15): Conv1d(384, 768, kernel_size=(8,), stride=(4,), bias=False)
        (16): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (17): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (18): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (19): LeakyReLU(negative_slope=0.2)
        (20): Conv1d(768, 1536, kernel_size=(4,), stride=(2,), bias=False)
        (21): LeakyReLU(negative_slope=0.2)
        (22): Conv1d(1536, 256, kernel_size=(3,), stride=(1,), bias=False)
      )
    )
  )
  (decoder): GeneratorV2(
    (net): CachedSequential(
      (0): Conv1d(128, 1536, kernel_size=(3,), stride=(1,), bias=False)
      (1): LeakyReLU(negative_slope=0.2)
      (2): ConvTranspose1d(1536, 768, kernel_size=(4,), stride=(2,), padding=(1,), bias=False)
      (3): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (4): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (5): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (6): LeakyReLU(negative_slope=0.2)
      (7): ConvTranspose1d(768, 384, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (8): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (9): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (10): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (11): LeakyReLU(negative_slope=0.2)
      (12): ConvTranspose1d(384, 192, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (13): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (14): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (15): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (16): LeakyReLU(negative_slope=0.2)
      (17): ConvTranspose1d(192, 96, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (18): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (19): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (20): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (21): LeakyReLU(negative_slope=0.2)
      (22): Conv1d(96, 16, kernel_size=(7,), stride=(1,), bias=False)
    )
  )
  (discriminator): CombineDiscriminators(
    (discriminators): ModuleList(
      (0): MultiPeriodDiscriminator(
        (layers): ModuleList(
          (0): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (1): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (2): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (3): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (4): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
        )
      )
      (1): MultiScaleDiscriminator(
        (layers): ModuleList(
          (0): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
          (1): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
          (2): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
        )
      )
    )
  )
  (audio_distance): AudioDistanceV1(
    (multiscale_stft): MultiScaleSTFT(
      (stfts): ModuleList(
        (0): Spectrogram()
        (1): Spectrogram()
        (2): Spectrogram()
        (3): Spectrogram()
        (4): Spectrogram()
      )
      (mel_scales): ModuleList(
        (0): None
        (1): None
        (2): None
        (3): None
        (4): None
      )
    )
  )
  (multiband_audio_distance): AudioDistanceV1(
    (multiscale_stft): MultiScaleSTFT(
      (stfts): ModuleList(
        (0): Spectrogram()
        (1): Spectrogram()
        (2): Spectrogram()
        (3): Spectrogram()
        (4): Spectrogram()
      )
      (mel_scales): ModuleList(
        (0): None
        (1): None
        (2): None
        (3): None
        (4): None
      )
    )
  )
)
train set: 53 examples
val set: 2 examples
selected gpu: []
Traceback (most recent call last):
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jake\anaconda3\envs\rave_env\Scripts\rave.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\scripts\main_cli.py", line 28, in main
    app.run(train.main)
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\scripts\train.py", line 124, in main
    trainer = pl.Trainer(
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 419, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py", line 193, in __init__
    self._check_device_config_and_set_final_flags(
  File "C:\Users\Jake\anaconda3\envs\rave_env\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py", line 435, in _check_device_config_and_set_final_flags
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: `Trainer(devices=[])` value is not a valid input using cuda accelerator.
```

**Comment by joetorsney** [comment]
try `--gpu 0` at the end of rave train?

**Comment by jacklion710** [comment]
> try `--gpu 0` at the end of rave train?

Yep that's what solved it! Thanks for your input.
