### ISSUE TITLE
exporting path error

### ISSUE THREAD

**Issue by gyuchulm** [acids-ircam/RAVE#171]
```
(rave) C:\Users\USER>rave export --run C:\Users\USER\Rave\Dataset\Drum (--streaming)
INFO:root:library loading
INFO:root:DEBUG
I0204 01:52:58.200918  6008 export.py:206] building rave
I0204 01:52:58.200918  6008 resource_reader.py:50] system_path_file_exists:C:\Users\USER\Rave\Dataset\Drum\config.gin
E0204 01:52:58.200918  6008 resource_reader.py:55] Path not found: C:\Users\USER\Rave\Dataset\Drum\config.gin
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\rave\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\anaconda3\envs\rave\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\anaconda3\envs\rave\Scripts\rave.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\anaconda3\envs\rave\lib\site-packages\scripts\main_cli.py", line 32, in main
    app.run(export.main)
  File "C:\Users\USER\anaconda3\envs\rave\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\USER\anaconda3\envs\rave\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\USER\anaconda3\envs\rave\lib\site-packages\scripts\export.py", line 208, in main
    gin.parse_config_file(os.path.join(FLAGS.run, "config.gin"),
  File "C:\Users\USER\anaconda3\envs\rave\lib\site-packages\gin\config.py", line 2457, in parse_config_file
    raise IOError(err_str.format(config_file, prefixes))
OSError: Unable to open file: C:\Users\USER\Rave\Dataset\Drum\config.gin. Searched config paths: [''].
```

I've trained the model with that directory named with same with the folder, 
Is there any missing what I did? and where is the config.gin file?
for the directory, Is that correct the path of training data?

**Comment by ign3ousr0ck** [comment]
I'm having this same issue, could you please explain how you solved it?

**Comment by gyuchulm** [comment]
Did you run on the anaconda? I installed the anaconda on the user folder; there is another "run" folder in it from the data set. The run folder saves as "name + 6~8?? number string". config gin file is in there, so you should find the run folder and put the address of the run folder while you export :)
