### ISSUE TITLE
Misconfiguration Exception raised when training

### ISSUE THREAD

**Issue by jacklion710** [acids-ircam/RAVE#192]
I've been struggling to begin training with hardware acceleration using my NVIDIA 3080ti. I've run through the process so many different ways but I keep getting stuck when using `rave train ...`
When running `python -c "import torch; print(torch.cuda.is_available())"` "True" is returned. Below are the commands I am running from creation to training. I have CUDA installed and I am using miniconda3 to create a conda environment.  I also noticed that in [train_setup](https://github.com/acids-ircam/RAVE/blob/master/docs/training_setup.md) there is a line that says, "you can now use python cli_helper.py to start a new training !" But I have not found the file cli_helper.py. Would someone be able to explain what I am missing or doing wrong?
```
conda create -n myrave python=3.9 anaconda

conda activate myrave

cd C:\Users\Jake\miniconda3\envs\myrave

git clone https://github.com/acids-ircam/RAVE
cd RAVE
pip install -r requirements.txt

conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

pip install acids-rave

conda install ffmpeg

rave preprocess --input_path C:\Users\Jake\Desktop\Roar-Samps --output_path C:\Users\Jake\Desktop\Dataset (--lazy)

rave train --config v2 --db_path C:\Users\Jake\Desktop\Dataset --name jl-sounds-study
```
Upon running the final line in the above script, the following error is returned...
```
selected gpu: []
Traceback (most recent call last):
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jake\miniconda3\envs\myrave\Scripts\rave.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\scripts\main_cli.py", line 28, in main
    app.run(train.main)
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\scripts\train.py", line 131, in main
    trainer = pl.Trainer(
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 420, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py", line 192, in __init__
    self._check_device_config_and_set_final_flags(
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py", line 434, in _check_device_config_and_set_final_flags
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: `Trainer(devices=[])` value is not a valid input using cuda accelerator.
```

**Comment by devstermarts** [comment]
Try using --gpu 0 (and potentially --gpu 1 --gpu 2 ...) as parameters on rave train.

**Comment by caillonantoine** [comment]
I think I know what the problem is. By default, rave tries to find a _free_ gpu (free is defined as a threshold over the memory consumption). I think since you are using a Desktop GPU and not a compute server, a small (?) amount of RAM is already allocated by your graphical env, which makes rave think no _free_ gpu is available. I'll think of a way to fix that.

**Comment by jacklion710** [comment]
> Try using --gpu 0 (and potentially --gpu 1 --gpu 2 ...) as parameters on rave train.

`rave train --config v2 --gpu 0 --db_path C:\Users\Jake\Desktop\Dataset --name jl-sounds-study` actually does in fact work. Is there more documentation I am missing somewhere? Because I had no idea about this flag in particular.

**Comment by caillonantoine** [comment]
you can use `rave train --help` to get a list of all the flags :)

**Comment by jacklion710** [comment]
> you can use `rave train --help` to get a list of all the flags :)

Awesome, thank you! One weird thing I do want to mention before moving on, I notice a faint but consistent rattling sound coming out of my speaker monitors only while training is active. Ending the process gets rid of the sound. No big deal really, just thought that was a bit of an odd side effect.
