### ISSUE TITLE
Resume training: Runtime error when loading state_dict (size mismatch in torch.Size)

### ISSUE THREAD

**Issue by devstermarts** [acids-ircam/RAVE#196]
Hey. I'm getting a runtime error after resuming a training that's been running (and previously resumed) until yesterday. The training parameters have not been changed so I can't really make sense of the error log here. Can anyone help?

```
File "/content/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RAVE: 
size mismatch for decoder.net.22.weight_g: copying a param with shape torch.Size([16, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 1, 1]). 
size mismatch for decoder.net.22.weight_v: copying a param with shape torch.Size([16, 96, 7]) from checkpoint, the shape in current model is torch.Size([32, 96, 7]).
```
Training params as set here: 

```
!/content/miniconda/bin/rave train --config v2.gin --config wassertein --override LATENT_SIZE=16 --db_path /content/drive/MyDrive/kerner/meta/ --name kerner_ld16 --ckpt /content/drive/MyDrive/kerner/save/runs/kerner_ld16_7f75f71f61/version_5/checkpoints/`
```

Full log/ output: 
```
I0219 16:15:00.698927 140319021629824 resource_reader.py:50] system_path_file_exists:v2.gin
E0219 16:15:00.699349 140319021629824 resource_reader.py:55] Path not found: v2.gin
I0219 16:15:00.699469 140319021629824 resource_reader.py:50] system_path_file_exists:/content/miniconda/lib/python3.9/site-packages/rave/v2.gin
E0219 16:15:00.699545 140319021629824 resource_reader.py:55] Path not found: /content/miniconda/lib/python3.9/site-packages/rave/v2.gin
I0219 16:15:00.700514 140319021629824 resource_reader.py:50] system_path_file_exists:configs/v1.gin
E0219 16:15:00.700716 140319021629824 resource_reader.py:55] Path not found: configs/v1.gin
I0219 16:15:00.720617 140319021629824 resource_reader.py:50] system_path_file_exists:wassertein.gin
E0219 16:15:00.720851 140319021629824 resource_reader.py:55] Path not found: wassertein.gin
I0219 16:15:00.720940 140319021629824 resource_reader.py:50] system_path_file_exists:/content/miniconda/lib/python3.9/site-packages/rave/wassertein.gin
E0219 16:15:00.721038 140319021629824 resource_reader.py:55] Path not found: /content/miniconda/lib/python3.9/site-packages/rave/wassertein.gin
RAVE(
  (pqmf): CachedPQMF(
    (forward_conv): Conv1d(1, 16, kernel_size=(513,), stride=(16,), bias=False)
    (inverse_conv): Conv1d(16, 16, kernel_size=(33,), stride=(1,), bias=False)
  )
  (encoder): WasserteinEncoder(
    (encoder): Encoder(
      (net): CachedSequential(
        (0): Conv1d(16, 96, kernel_size=(7,), stride=(1,), bias=False)
        (1): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): LeakyReLU(negative_slope=0.2)
        (3): Conv1d(96, 192, kernel_size=(9,), stride=(4,), bias=False)
        (4): BatchNorm1d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): LeakyReLU(negative_slope=0.2)
        (6): Conv1d(192, 384, kernel_size=(9,), stride=(4,), bias=False)
        (7): BatchNorm1d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (8): LeakyReLU(negative_slope=0.2)
        (9): Conv1d(384, 768, kernel_size=(9,), stride=(4,), bias=False)
        (10): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (11): LeakyReLU(negative_slope=0.2)
        (12): Conv1d(768, 1536, kernel_size=(5,), stride=(2,), bias=False)
        (13): LeakyReLU(negative_slope=0.2)
        (14): Conv1d(1536, 16, kernel_size=(5,), stride=(1,), bias=False)
      )
    )
  )
  (decoder): GeneratorV2(
    (net): CachedSequential(
      (0): Conv1d(16, 1536, kernel_size=(3,), stride=(1,), bias=False)
      (1): LeakyReLU(negative_slope=0.2)
      (2): ConvTranspose1d(1536, 768, kernel_size=(4,), stride=(2,), padding=(1,), bias=False)
      (3): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (4): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (5): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (6): LeakyReLU(negative_slope=0.2)
      (7): ConvTranspose1d(768, 384, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (8): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (9): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (10): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (11): LeakyReLU(negative_slope=0.2)
      (12): ConvTranspose1d(384, 192, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (13): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (14): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (15): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (16): LeakyReLU(negative_slope=0.2)
      (17): ConvTranspose1d(192, 96, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (18): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (19): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (20): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (21): LeakyReLU(negative_slope=0.2)
      (22): Conv1d(96, 32, kernel_size=(7,), stride=(1,), bias=False)
    )
  )
  (discriminator): CombineDiscriminators(
    (discriminators): ModuleList(
      (0): MultiPeriodDiscriminator(
        (layers): ModuleList(
          (0): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (1): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (2): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (3): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (4): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
        )
      )
      (1): MultiScaleDiscriminator(
        (layers): ModuleList(
          (0): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
          (1): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
          (2): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
        )
      )
    )
  )
  (audio_distance): AudioDistanceV1(
    (multiscale_stft): MultiScaleSTFT(
      (stfts): ModuleList(
        (0): Spectrogram()
        (1): Spectrogram()
        (2): Spectrogram()
        (3): Spectrogram()
        (4): Spectrogram()
      )
      (mel_scales): ModuleList(
        (0): None
        (1): None
        (2): None
        (3): None
        (4): None
      )
    )
  )
  (multiband_audio_distance): AudioDistanceV1(
    (multiscale_stft): MultiScaleSTFT(
      (stfts): ModuleList(
        (0): Spectrogram()
        (1): Spectrogram()
        (2): Spectrogram()
        (3): Spectrogram()
        (4): Spectrogram()
      )
      (mel_scales): ModuleList(
        (0): None
        (1): None
        (2): None
        (3): None
        (4): None
      )
    )
  )
)
train set: 1037 examples
val set: 22 examples
/content/miniconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
selected gpu: [0]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at /content/drive/MyDrive/kerner/save/runs/kerner_ld16_7f75f71f61/version_5/checkpoints/last.ckpt
Traceback (most recent call last):
  File "/content/miniconda/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/content/miniconda/lib/python3.9/site-packages/scripts/main_cli.py", line 28, in main
    app.run(train.main)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/miniconda/lib/python3.9/site-packages/scripts/train.py", line 163, in main
    trainer.fit(model, train, val, ckpt_path=run)
  File "/content/miniconda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/content/miniconda/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/content/miniconda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/content/miniconda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1056, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/content/miniconda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/content/miniconda/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 261, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/content/miniconda/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/content/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RAVE:
	size mismatch for decoder.net.22.weight_g: copying a param with shape torch.Size([16, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 1, 1]).
	size mismatch for decoder.net.22.weight_v: copying a param with shape torch.Size([16, 96, 7]) from checkpoint, the shape in current model is torch.Size([32, 96, 7]).
```

**Comment by devstermarts** [comment]
Solved by using RAVE v2.1.7 instead of v2.1.8 from yesterday.
