### ISSUE TITLE
Error exporting model trained with spherical regularization

### ISSUE THREAD

**Issue by JoshuaAuros** [acids-ircam/RAVE#197]
Hello, I attempted to export a model (v2) with the spherical configuration and received this error. 
```
INFO:root:library loading
INFO:root:DEBUG
I0220 17:11:55.433522  2464 export.py:206] building rave
Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python310\Scripts\rave.exe\__main__.py", line 7, in <module>
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python310\lib\site-packages\scripts\main_cli.py", line 32, in main
    app.run(export.main)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python310\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python310\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python310\lib\site-packages\scripts\export.py", line 228, in main
    raise ValueError(f"Encoder type {type(pretrained.encoder)} "
ValueError: Encoder type <class 'rave.blocks.SphericalEncoder'> not supported for export.
```

I've been able to export models with a few different configurations, so far this is the only one that isn't working for me. If anyone knows what might be causing this issue, I would be very grateful to hear your insight.

**Comment by caillonantoine** [comment]
Oops ! I'll fix this asap !

**Comment by caillonantoine** [comment]
It should be fixed now :)

**Comment by JoshuaAuros** [comment]
Exporting works now after updating!
