### ISSUE TITLE
Memory errors training discrete architecture

### ISSUE THREAD

**Issue by jreus** [acids-ircam/RAVE#222]
Hey RAVE team, I'm encountering what looks like a bug when trying to train a discrete model with cached convolutions.
I've tried training both a v2 and discrete model on the same dataset:
```
rave train --config v2 --config causal --db_path ~/datasets/preprocessed/MyDataset --name Training-V2
rave train --config discrete --config causal --db_path ~/datasets/preprocessed/MyDataset --name Training-Discrete
```
This is being done on a NVIDIA TITAN V with 12GB of ram. While the v2 model has been training steadily at around 9GB of RAM usage, the discrete model trains up to around 200K steps, sits at around 4GB for a while and then crashes with a CUDA memory error.

Any idea what could be the issue? Here's the error dump!

```
~$ CUDA_VISIBLE_DEVICES=0 rave train --config discrete --config causal --d
b_path ~/datasets/preprocessed/MyDataset --name Training-discrete --ckpt ~/runs/Training-discrete                                                                      

I0321 09:45:20.124982 139884216475776 resource_reader.py:50] system_path_file_exists:discrete.
gin                                                                                           
E0321 09:45:20.125326 139884216475776 resource_reader.py:55] Path not found: discrete.gin     
I0321 09:45:20.125427 139884216475776 resource_reader.py:50] system_path_file_exists:/its/home
/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/rave/discrete.gin                   
E0321 09:45:20.125514 139884216475776 resource_reader.py:55] Path not found: /its/home/jojojo/m
iniconda3/envs/rave2/lib/python3.10/site-packages/rave/discrete.gin                           
I0321 09:45:20.125863 139884216475776 resource_reader.py:50] system_path_file_exists:configs/v
2.gin                                                                                         
E0321 09:45:20.126039 139884216475776 resource_reader.py:55] Path not found: configs/v2.gin   
I0321 09:45:20.126696 139884216475776 resource_reader.py:50] system_path_file_exists:configs/v
1.gin                                                                                         
E0321 09:45:20.126865 139884216475776 resource_reader.py:55] Path not found: configs/v1.gin   
I0321 09:45:20.149399 139884216475776 resource_reader.py:50] system_path_file_exists:causal.gi
n                                                                                             
E0321 09:45:20.149617 139884216475776 resource_reader.py:55] Path not found: causal.gin       
I0321 09:45:20.149685 139884216475776 resource_reader.py:50] system_path_file_exists:/its/home
/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/rave/causal.gin                     
E0321 09:45:20.149741 139884216475776 resource_reader.py:55] Path not found: /its/home/jojojo/m
iniconda3/envs/rave2/lib/python3.10/site-packages/rave/causal.gin   

 << ... long print out of model architecture removed to save space ... >>

train set: 995 examples                                                                       
val set: 21 examples                                                                          
selected gpu: [0]                                                                             
GPU available: True (cuda), used: True                                                        
TPU available: False, using: 0 TPU cores                                                      
IPU available: False, using: 0 IPUs                                                           
HPU available: False, using: 0 HPUs                                                           
Restoring states from the checkpoint path at /its/home/jojojo/runs/Gloria-base-discrete_a45605d
7ee/version_0/checkpoints/last-v1.ckpt                                                        
/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/callbacks
/model_checkpoint.py:337: UserWarning: The dirpath has changed from 'runs/Gloria-base-discrete
_a45605d7ee/version_0/checkpoints' to 'runs/Gloria-base-discrete_a45605d7ee/version_4/checkpoi
nts', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and 
`best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.                   
  warnings.warn(                                                                              
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]                                                     
                                                                                              
  | Name                     | Type                  | Params                                 
-------------------------------------------------------------------                           
0 | pqmf                     | CachedPQMF            | 16.7 K                                 
1 | encoder                  | DiscreteEncoder       | 14.3 M                                 
2 | decoder                  | GeneratorV2           | 14.9 M                                 
3 | discriminator            | CombineDiscriminators | 27.1 M                                 
4 | audio_distance           | AudioDistanceV1       | 0                                      
5 | multiband_audio_distance | AudioDistanceV1       | 0                                      
-------------------------------------------------------------------                           
56.3 M    Trainable params                                                                    
0         Non-trainable params                                                                
56.3 M    Total params                                                                        
225.297   Total estimated model params size (MB)                                              
Restored all states from the checkpoint file at /its/home/jojojo/runs/Gloria-base-discrete_a456
05d7ee/version_0/checkpoints/last-v1.ckpt                                                     
Epoch 1600:   0%|                                            | 0/124 [00:00<?, ?it/s, v_num=4]
/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/trainer/c
onnectors/logger_connector/result.py:232: UserWarning: You called `self.log('scale_multiband_s
pectral_distance', ...)` in your `training_step` but the value needs to be floating point. Con
verting it to torch.float32.                                                                  
  warning_cache.warn(                                                                         
/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/trainer/c
onnectors/logger_connector/result.py:232: UserWarning: You called `self.log('scale_fullband_sp
ectral_distance', ...)` in your `training_step` but the value needs to be floating point. Conv
erting it to torch.float32.                                                                   
  warning_cache.warn(  

Epoch 1612:  91%|██████████████████████████████▉   | 113/124 [00:35<00:03,  3.19it/s, v_num=4]
Traceback (most recent call last):                                                            
  File "/its/home/jojojo/miniconda3/envs/rave2/bin/rave", line 8, in <module>                  
    sys.exit(main())                                                                          
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/scripts/main_cli.py
", line 28, in main                                                                           
    app.run(train.main)                                                                       
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/absl/app.py", line 
308, in run                                                                                   
    _run_main(main, args)                                                                     
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/absl/app.py", line 
254, in _run_main                                                                             
    sys.exit(main(argv))                                                                      
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/scripts/train.py", 
line 160, in main                                                                             
    trainer.fit(model, train, val, ckpt_path=run)                                             
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/t
rainer/trainer.py", line 608, in fit                                                          
    call._call_and_handle_interrupt(                                                          
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/t
rainer/call.py", line 38, in _call_and_handle_interrupt                                       
    return trainer_fn(*args, **kwargs)                                                        
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/t
rainer/trainer.py", line 650, in _fit_impl                                                    
    self._run(model, ckpt_path=self.ckpt_path)                                                
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/t
rainer/trainer.py", line 1103, in _run                                                        
    results = self._run_stage()                                                               
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/t
rainer/trainer.py", line 1182, in _run_stage                                                  
    self._run_train()                                                                         
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/$oops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/$oops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/$oops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lig[0/1973]rainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 90, in advance
    outputs = self.manual_loop.run(kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual_loop.py", line 110, in advance
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1485, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/rave/model.py", line 276, in training_step
    self.balancer.backward(loss_gen, y_multiband, self.log, p.tick)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/rave/balancer.py",
line 55, in backward
    grads[k], = torch.autograd.grad(
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 11.78 GiB total capacity; 10.92 GiB already allocated; 53.62 MiB free; 11.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Epoch 1612:  91%|█████████ | 113/124 [00:36<00:03,  3.09it/s, v_num=4]
```

**Comment by moiseshorta** [comment]
Looks like an OOM error when the model shifts to training phase 2, try with a smaller batch size

**Comment by jreus** [comment]
> Looks like an OOM error when the model shifts to training phase 2, try with a smaller batch size

Thanks @moiseshorta ~ I think that's the issue. I had similar errors on this same machine with the old v1 architecture when the GAN phase would kick in after 1M steps. The solution for me then was to resume the training starting in the GAN phase with `warmup 0` ...I never had to change the batch size then, it seems like there's an unusually high memory spike that happens during the training phase shift, but not before or after.
