### ISSUE TITLE
Error with preprocessing script - UnboundLocalError: local variable 'n_seconds' referenced before assignment

### ISSUE THREAD

**Issue by jreus** [acids-ircam/RAVE#224]
Has anyone encountered errors with `n_seconds` in `preprocess.py`? I'm getting the following. Which is a bit weird because I had no issues preprocessing other datasets!

```
$ rave preprocess --input_path ~/datasets/MyDataset --output_path ~/datasets/preprocessed/MyDataset
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/its/home/jojojo/miniconda3/envs/rave2/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/scripts/main_cli.py", line 36, in main
    app.run(preprocess.main)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/its/home/jojojo/miniconda3/envs/rave2/lib/python3.10/site-packages/scripts/preprocess.py", line 231, in main
    yaml.safe_dump({'lazy': FLAGS.lazy, 'n_seconds': n_seconds}, metadata)
UnboundLocalError: local variable 'n_seconds' referenced before assignment
```

**Comment by bliptripmusic** [comment]
Yes, I just encountered this too. I found using `--lazy` resolved it. For some reason it's not setting the lazy mode to either true or false which creates the `UnboundLocalError.`
