### ISSUE TITLE
ValueError: n_components=128 must be between 0 and min(n_samples, n_features)=64 with svd_solver='full'

### ISSUE THREAD

**Issue by fferri** [acids-ircam/RAVE#249]
Similar to #248 I have to use --gpu -1 because I am on a Mac M1.

This time I tried to install acids-rave from the git repo:

```
$ RAVE_VERSION=2.2.3 python3.10 -m pip install .
```

(strangely, due to dependencies constraints, python3.11 doesn't work)

It fails training with:

```
$ rave train --config v2 --db_path . --name J6-madness-1 --gpu -1
...
train set: 46 examples
val set: 1 examples
selected gpu: 0
GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:200: UserWarning: MPS available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='mps', devices=1)`.
  rank_zero_warn(

  | Name                     | Type                  | Params
-------------------------------------------------------------------
0 | pqmf                     | CachedPQMF            | 16.7 K
1 | encoder                  | VariationalEncoder    | 16.1 M
2 | decoder                  | GeneratorV2           | 15.5 M
3 | discriminator            | CombineDiscriminators | 27.1 M
4 | audio_distance           | AudioDistanceV1       | 0
5 | multiband_audio_distance | AudioDistanceV1       | 0
-------------------------------------------------------------------
58.7 M    Trainable params
0         Non-trainable params
58.7 M    Total params
234.734   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Sanity Checking DataLoader 0: 100%|█████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.29it/s]Computing receptive field for this configuration...
Compression ratio: 2048x (~21.5Hz @ 44100Hz)
Receptive field: 614.90ms <-- x --> 599.27ms
Traceback (most recent call last):
  File "/opt/homebrew/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/scripts/main_cli.py", line 30, in main
    app.run(train.main)
  File "/opt/homebrew/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/homebrew/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/homebrew/lib/python3.10/site-packages/scripts/train.py", line 213, in main
    trainer.fit(model, train, val, ckpt_path=run)
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 206, in run
    output = self.on_run_end()
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 180, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 288, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1347, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/rave/model.py", line 408, in validation_epoch_end
    pca = PCA(z.shape[-1]).fit(z.cpu().numpy())
  File "/opt/homebrew/lib/python3.10/site-packages/sklearn/base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/sklearn/decomposition/_pca.py", line 434, in fit
    self._fit(X)
  File "/opt/homebrew/lib/python3.10/site-packages/sklearn/decomposition/_pca.py", line 510, in _fit
    return self._fit_full(X, n_components)
  File "/opt/homebrew/lib/python3.10/site-packages/sklearn/decomposition/_pca.py", line 524, in _fit_full
    raise ValueError(
ValueError: n_components=128 must be between 0 and min(n_samples, n_features)=64 with svd_solver='full'
```

Is it because of my dataset is too small?

Some info on my system:
```
$ python3.10 --version
Python 3.10.12
```

```
$ python3.10 -m pip list | grep numpy
numpy 1.24.4
```

```
$ uname -m
arm64
```

**Comment by domkirke** [comment]
Hello @fferri ,
yes your dataset is too small, such that the number of items is lower that the number of batches used to compute the PCA. Try with a wider dataset!
