### ISSUE TITLE
Exception generating exporting a model with prior

### ISSUE THREAD

**Issue by blazejkotowski** [acids-ircam/RAVE#279]
1. I have preprocessed the data following way:
`rave preprocess --channels 1 --input_path <input_path> --output_path <db_path>`

2. Then I trained the model with following command
`rave train --batch 2 --channels 1 --db_path <db_path> --name <run_name> --out_path <run_out> --val_every 2500 --config v2.gin`

3. Then I trained the prior
`rave train_prior --db_path <db_path> --name <prior_name> --out_path <prior_out_path> --val_every 2500 --gpu 0`

4. Finally, on the export with the following command
`rave export organizmo_fire --streaming true --run <run_out_path> --prior <prior_out_path> --output ts_models/`

I get the following exception
```
Traceback (most recent call last):
  File "/miniconda/bin/rave", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/miniconda/lib/python3.11/site-packages/scripts/main_cli.py", line 38, in main
    app.run(export.main)
  File "/miniconda/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/miniconda/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/miniconda/lib/python3.11/site-packages/scripts/export.py", line 566, in main
    scripted_rave = script_class(
                    ^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/site-packages/scripts/export.py", line 197, in __init__
    self.register_method(
  File "/miniconda/lib/python3.11/site-packages/nn_tilde/__init__.py", line 102, in register_method
    y = getattr(self, method_name)(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/site-packages/scripts/export.py", line 345, in prior
    return self.prior_module.forward(temp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/site-packages/scripts/export.py", line 464, in forward
    x[..., i:i + 1] = self.step_forward(temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/site-packages/scripts/export.py", line 445, in step_forward
    self.previous_step.copy_(x.clone())
RuntimeError: output with shape [1, 128, 1] doesn't match the broadcast shape [4, 128, 1]
```

At the same time, I am able to export the model without prior. What is the issue?

**Comment by alfredolozano** [comment]
I have the same problem, I think @ballerburg9005 suggests to train with msprior here: https://github.com/acids-ircam/RAVE/discussions/300 

But I'm not sure it works, and how.

**Comment by audiophil-dev** [comment]
Same error here. Has anyone managed to train and export a prior (not msprior) model that can be used with `nn~`, using a version of this repo later than v1?

**Comment by elgiano** [comment]
I'm looking into it and I have been able to export priors with models later than v2, by applying two changes to `scripts/export.py`.

In `ScriptedRave.__init__`, I added cached conv initialization before `register_method("prior")`, and then also disabled `test_method`, since testing with multichannel (batch_size=4) was failing and I didn't manage to figure out whether we can make it work.
```python
        if prior is not None:
            self._has_prior = True
            self.prior_module = prior

            # change 1: have to init cached conv before graphing
            z = self.prior_module.forward(torch.zeros(1, self.n_channels, self.full_latent_size))

            self.register_method(
                "prior",
                in_channels=1,
                in_ratio=prior.ratio,
                out_channels = self.latent_size,
                out_ratio=prior.ratio,
                # change 2: disable model testing
                test_method=False
            )
```
<details>
<summary>here is the patch</summary>

```diff
diff --git a/scripts/export.py b/scripts/export.py
index e0ce83d..a459059 100644
--- a/scripts/export.py
+++ b/scripts/export.py
@@ -194,12 +194,17 @@ class ScriptedRAVE(nn_tilde.Module):
         if prior is not None:
             self._has_prior = True
             self.prior_module = prior
+
+            # have to init cached conv before graphing
+            z = self.prior_module.forward(torch.zeros(1, self.n_channels, self.full_latent_size))
+
             self.register_method(
                 "prior",
                 in_channels=1,
                 in_ratio=prior.ratio,
                 out_channels = self.latent_size,
-                out_ratio=prior.ratio
+                out_ratio=prior.ratio,
+                test_method=False
             )
         else:
             self.prior_module = DumbPrior()
```

</details>
