### ISSUE TITLE
train_prior error

### ISSUE THREAD

**Issue by bertrandclim** [acids-ircam/RAVE#281]
Hi,

I have a v2 RAVE model (default config) trained in v2.2.2, which works fine to export and play. I then upgraded to v2.3.1 and attempted to train a prior for this model with
 `rave train_prior --model runs/birdfrog1_fe77618ebd/version_9/ --db_path datasets/birdfrog1/ --out_path priors`
but received the following error message:
```
/home/username/miniconda3/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
model found : runs/birdfrog1_fe77618ebd/version_9/checkpoints/best.ckpt
Traceback (most recent call last):
  File "/home/username/miniconda3/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/home/username/miniconda3/lib/python3.9/site-packages/scripts/main_cli.py", line 34, in main
    app.run(train_prior.main)
  File "/home/username/miniconda3/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/username/miniconda3/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/username/miniconda3/lib/python3.9/site-packages/scripts/train_prior.py", line 106, in main
    prior = rave.prior.VariationalPrior(pretrained_vae=pretrained)
  File "/home/username/miniconda3/lib/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/username/miniconda3/lib/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/username/miniconda3/lib/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/username/miniconda3/lib/python3.9/site-packages/rave/prior/model.py", line 36, in __init__
    raise RuntimeError('please init Prior with either fidelity or latent_size keywords')
RuntimeError: please init Prior with either fidelity or latent_size keywords
  In call to configurable 'VariationalPrior' (<class 'rave.prior.model.VariationalPrior'>)
```
When I specify either latent_size or fidelity with a custom .gin file, I receive a new error during the data loading stage which I'm happy to share if it's of interest. This is on Python 3.9, Debian 10, RAVE 2.3.1, and Torch 2.1.2.

**Comment by delmenhorst** [comment]
same here!

**Comment by fokklz** [comment]
I guess I should have checked beforehand, did not see this issue. But I had the same issue and also found a workaround. This might help you as well.

-> #314
