### ISSUE TITLE
training fails 

### ISSUE THREAD

**Issue by genevera** [acids-ircam/RAVE#289]
```
rave train --name ok --out_path /trained --db_path /worked --config v2
I0214 03:23:52.897175 140638120218624 resource_reader.py:50] system_path_file_exists:v2.gin
E0214 03:23:52.897490 140638120218624 resource_reader.py:55] Path not found: v2.gin
I0214 03:23:52.897578 140638120218624 resource_reader.py:50] system_path_file_exists:/usr/local/lib/python3.10/dist-packages/rave/v2.gin
E0214 03:23:52.897640 140638120218624 resource_reader.py:55] Path not found: /usr/local/lib/python3.10/dist-packages/rave/v2.gin
I0214 03:23:52.898360 140638120218624 resource_reader.py:50] system_path_file_exists:configs/v1.gin
E0214 03:23:52.898536 140638120218624 resource_reader.py:55] Path not found: configs/v1.gin
/usr/local/lib/python3.10/dist-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Traceback (most recent call last):
  File "/usr/local/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/scripts/main_cli.py", line 30, in main
    app.run(train.main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.10/dist-packages/scripts/train.py", line 159, in main
    model = rave.RAVE(n_channels=FLAGS.channels)
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.10/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rave/model.py", line 188, in __init__
    self.decoder = decoder(n_channels=n_channels)
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.10/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 516, in meta_call_wrapper
    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rave/blocks.py", line 675, in __init__
    waveform_module = normalization(
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.10/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rave/blocks.py", line 20, in normalization
    return weight_norm(module)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py", line 109, in weight_norm
    WeightNorm.apply(module, name, dim)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py", line 48, in apply
    module.register_parameter(name + '_g', Parameter(norm_except_dim(weight, 2, dim).data))
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
  In call to configurable 'normalization' (<function normalization at 0x7fe8248db130>)
  In call to configurable 'GeneratorV2' (<class 'rave.blocks.GeneratorV2'>)
  In call to configurable 'RAVE' (<class 'rave.model.RAVE'>)
```

I get this reshape error no matter what I do.. I have a directory full of 48k ogg fils that all preprocess just fine but i can't seem to get the `train` command workng.

**Comment by genevera** [comment]
Actually I did get beyond this by adding --channels 1
