### ISSUE TITLE
train_prior broken

### ISSUE THREAD

**Issue by fokklz** [acids-ircam/RAVE#314]
Hey,

I love the project, but I'm not thrilled with the limited to non-existent documentation. However, I understand this is an early stage, and I've managed to get most things working without any issues so far.

The following command was used for all prior initializations:
`rave train_prior --model /mnt/ai-models/flz_mono_95639eacc0 --db_path /mnt/d/dataset_mono --out_path /mnt/ai-models/flz_mono_95639eacc0_prior --name flz_mono_prior`

Initially, I was running the version provided by pip, acquired using: pip install acids-rave. When running the train_prior command, the configuration was missing.

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/RAVE/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/scripts/main_cli.py", line 34, in main
    app.run(train_prior.main)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/scripts/train_prior.py", line 99, in main
    gin.parse_config_files_and_bindings(
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 2497, in parse_config_files_and_bindings
    includes_and_imports = parse_config_file(config_file, skip_unknown)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 2457, in parse_config_file
    raise IOError(err_str.format(config_file, prefixes))
OSError: Unable to open file: prior/prior_v1.gin. Searched config paths: ['', PosixPath('/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/rave'), PosixPath('/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/rave/configs'), PosixPath('/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/rave/configs/augmentations')].
```
Since I could see the file in the repository, I decided to uninstall acids-rave and instead run: 
`pip install -e git+https://github.com/acids-ircam/RAVE.git@v2.3.1#egg=acids-rave`

After a quick installation, I ran the command again, which resulted in:
```shell
Traceback (most recent call last):
  File "/root/miniconda3/envs/RAVE/bin/rave", line 33, in <module>
    sys.exit(load_entry_point('acids-rave', 'console_scripts', 'rave')())
  File "/root/src/acids-rave/scripts/main_cli.py", line 34, in main
    app.run(train_prior.main)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/src/acids-rave/scripts/train_prior.py", line 99, in main
    gin.parse_config_files_and_bindings(
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 2497, in parse_config_files_and_bindings
    includes_and_imports = parse_config_file(config_file, skip_unknown)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 2450, in parse_config_file
    includes, imports = parse_config(f, skip_unknown=skip_unknown)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 2322, in parse_config
    for statement in parser:
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config_parser.py", line 211, in __next__
    statement = self.parse_statement()
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config_parser.py", line 244, in parse_statement
    statement, bindings = self._parse_binding_block(
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config_parser.py", line 465, in _parse_binding_block
    value = self.parse_value()
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config_parser.py", line 280, in parse_value
    success, value = parser()
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config_parser.py", line 558, in _maybe_parse_configurable_reference
    reference = self._delegate.configurable_reference(scoped_name, evaluate)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/utils.py", line 60, in try_with_location
    augment_exception_message_and_reraise(exception, _format_location(location))
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/utils.py", line 56, in try_with_location
    yield
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config_parser.py", line 558, in _maybe_parse_configurable_reference
    reference = self._delegate.configurable_reference(scoped_name, evaluate)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 844, in configurable_reference
    return ConfigurableReference(scoped_selector, evaluate)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 691, in __init__
    self.initialize()
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 697, in initialize
    _raise_unknown_reference_error(self)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 644, in _raise_unknown_reference_error
    raise ValueError(err_str.format(ref.selector, maybe_parens, additional_msg))
ValueError: No configurable matching reference '@get_model_sr()'.
  In file "/root/src/acids-rave/rave/configs/prior/prior_v1.gin", line 8
        sr=@get_model_sr()
```

Since I couldn't find any other definitions for @get_model_sr(), I edited the /root/src/acids-rave/rave/configs/prior/prior_v1.gin file directly and set sr=44100.

Running the command again resulted in:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/RAVE/bin/rave", line 33, in <module>
    sys.exit(load_entry_point('acids-rave', 'console_scripts', 'rave')())
  File "/root/src/acids-rave/scripts/main_cli.py", line 34, in main
    app.run(train_prior.main)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/src/acids-rave/scripts/train_prior.py", line 106, in main
    prior = rave.prior.VariationalPrior(pretrained_vae=pretrained)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/root/miniconda3/envs/RAVE/lib/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/root/src/acids-rave/rave/prior/model.py", line 36, in __init__
    raise RuntimeError('please init Prior with either fidelity or latent_size keywords')
```

Since there was no option for this, I edited `/root/src/acids-rave/rave/prior/model.py` and set a default value of `0.95` for fidelity.

## Quick re-run for anyone having the same issue:
```
pip uninstall acids-rave
pip install -e git+https://github.com/acids-ircam/RAVE.git@v2.3.1#egg=acids-rave
```
open `acids-rave/rave/configs/prior/prior_v1.gin` and replace `@get_model_sr()` with `44100`
open `acids-rave/rave/prior/model.py` and set a default value for `fidelity` for example `0.95`

The training can now be started.

**Comment by yusufbrima** [comment]
Hi

Thank you for sharing your workaround; it was incredibly helpful! Using your guidance, I managed to train a prior successfully. Now, I’m trying to integrate this prior into a Python script with a goal to sample from the prior and generate new audios but am running into some trouble. Since I’m fairly new to this, I haven’t found clear resources on how to proceed.

Here’s the code snippet I’ve put together so far:
```python
import hashlib
import os
import sys
from typing import Callable, Optional, Iterable, Dict, Any
import soundfile as sf
import numpy as np
import torch
import gin
import rave
import rave.core
import rave.prior
import rave.dataset
from rave.transforms import get_augmentations
from torch.utils.data import DataLoader


def save_wavefile(waveform, filename, sampling_rate):
    """Save a waveform as a .wav file."""
    waveform = waveform.cpu().numpy()  # Convert to NumPy array
    waveform = np.squeeze(waveform)    # Remove extra dimensions if needed
    sf.write(filename, waveform.T, sampling_rate)  # Save as a wave file


# Main function to load everything
def main(db_path, config_path, model_path, batch_size=8, num_signal=131072, channels=1, workers=8, augmentations=None):
    
    torch.set_float32_matmul_precision('high')
    torch.backends.cudnn.benchmark = True
    
    # Setting up dataset
    n_channels = rave.dataset.get_training_channels(db_path, channels)
    sr = 44100  # Example sample rate, adapt based on model configuration
    
    gin.parse_config_file(config_path)

    if augmentations:
        augmentations = get_augmentations()
        gin.bind_parameter('dataset.get_dataset.augmentations', augmentations)
    
    # Prepare dataset for inference
    dataset = rave.dataset.get_dataset(db_path, sr, num_signal, n_channels=n_channels)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=workers)

    # Load the pretrained RAVE model
    pretrained = rave.RAVE()
    checkpoint = torch.load(model_path, map_location='cpu')

    if "EMA" in checkpoint["callbacks"]:
        pretrained.load_state_dict(checkpoint["callbacks"]["EMA"], strict=False)
    else:
        pretrained.load_state_dict(checkpoint["state_dict"], strict=False)
    
    pretrained.eval()
    gin.clear_config()

    # Parse a prior config file, specific to your setup
    config_file = "<path_to_prior_config.gin>"  # Replace with actual path
    gin.parse_config_file(config_file)

    latent_dim = 8  # Example latent size, adjust as necessary

    # Load prior model
    if isinstance(pretrained.encoder, rave.blocks.VariationalEncoder):
        model = rave.prior.VariationalPrior(pretrained_vae=pretrained)
        print("Prior model loaded successfully!")
    else:
        raise NotImplementedError(f"Prior not implemented for encoder of type {type(pretrained.encoder)}")

if __name__ == "__main__":
    config_path = "<path_to_config.gin>"  # Replace with actual config path
    model_path = "<path_to_model.ckpt>"   # Replace with actual model checkpoint path
    db_path = "<path_to_dataset>"         # Replace with actual dataset path

    main(db_path, config_path, model_path)

```

If you have any suggestions or could point me toward useful resources for using the prior within this setup, I’d really appreciate it.

Thank you again for all your help!
