### ISSUE TITLE
RuntimeError when training prior

### ISSUE THREAD

**Issue by xyzalanix** [acids-ircam/RAVE#33]
I've been getting issues with the prior side of things for a few weeks now. I've been in between local and colab since I noticed CUDA was maybe an issue (I'm using a 3060 card and torch is often tricky).

Using torch==1.8.0+cu11.1, I succesfully trained and exported my ts model. When attempting to train prior I get this error:

`RuntimeError: cannot reshape tensor of 0 elements into shape [12, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous`

I think this is a symptom of compatibility issues and versioning, and would appreciate suggestions on this training pipeline, preferably avoiding the need to retrain with a specific code and torch versions (?...).

🙂

**Comment by xyzalanix** [comment]
Full traceback:
```
Traceback (most recent call last):
  File "/home/alanix/data/RAVE/testing/RAVE/train_prior.py", line 122, in <module>
    trainer.fit(model, train, val)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1122, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 158, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/alanix/anaconda3/envs/rave/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 178, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/alanix/data/RAVE/testing/RAVE/prior/model.py", line 144, in validation_step
    x = self.quantized_normal.encode(self.diagonal_shift(x))
  File "/home/alanix/data/RAVE/testing/RAVE/prior/core.py", line 24, in encode
    return self.to_stack_one_hot(x.long())
  File "/home/alanix/data/RAVE/testing/RAVE/prior/core.py", line 29, in to_stack_one_hot
    x = x.reshape(x.shape[0], x.shape[1], -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [12, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

```

**Comment by caillonantoine** [comment]
Have you changed anything in the training procedure ? How large is your dataset ?

**Comment by xyzalanix** [comment]
I have not changed training procedure. The dataset's mdb file is 768.9 mb, folder contains 14 wav files.

**Comment by xyzalanix** [comment]
Closing this issue as it might be too specific to my local Linux setup. I moved over to a Windows machine in a fresh CUDA 11.3 environment and am now able to train prior models with my pretrained rave files. 
Thanks @caillonantoine  :)

**Comment by moiseshorta** [comment]
Hey @xyzalanix was this issue ever solved in an Ubuntu environment? seems I am running into the same problem...
