### ISSUE TITLE
Error: 'Conv1d' object has no attribute 'cumulative_delay'' > when loading RAVE models

### ISSUE THREAD

**Issue by jreus** [acids-ircam/RAVE#39]
Hey there, I recently pulled the latest updates to the RAVE repository. I'm now trying to load a previously trained checkpoint and am receiving the error `AttributeError: 'Conv1d' object has no attribute 'cumulative_delay'`

The issue with the following line:
```
model = RAVE.load_from_checkpoint(model_path, strict=False).eval()
```

Where model_path is the filepath to a successfully trained RAVE model which has worked with the last major RAVE release. 

Here's the full stacktrace
```
Traceback (most recent call last):
  File "experiments/rave/run_rave.py", line 117, in <module>
    model = RAVE.load_from_checkpoint(model_path, strict=False).eval()
  File "miniconda3/envs/ancestor/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 153, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "miniconda3/envs/ancestor/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 195, in _load_model_state
    model = cls(**_cls_kwargs)
  File "experiments/rave/rave/model.py", line 440, in __init__
    self.encoder = Encoder(
  File "experiments/rave/rave/model.py", line 325, in __init__
    cumulative_delay=net[-3].cumulative_delay,
  File "miniconda3/envs/ancestor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv1d' object has no attribute 'cumulative_delay'
```

**Comment by caillonantoine** [comment]
Hi :) as stated in the readme, you should update your dependencies too 

ˋpip install -r requirements.txt`

**Comment by jreus** [comment]
Thanks @caillonantoine - I've been trying to get RAVE to work within the same anaconda environment as a few other deep learning modules, so there was a bit of fiddling around getting all the dependencies to work. Everything is working happily now with the latest RAVE. :-)

However, I am getting some warnings when using my pre-existing trained models. Are these anything to be worried about? Synthesis still seems to work and the output wav file is indeed saved successfully.

```
lib/python3.9/site-packages/pytorch_lightning/core/saving.py:213: UserWarning: Found keys that are in the model state dict but not in the checkpoint: ['discriminator.discriminators.0.net.0.weight_g', 'discriminator.discriminators.0.net.0.weight_v', 'discriminator.discriminators.0.net.2.weight_g', 'discriminator.discriminators.0.net.2.weight_v', 'discriminator.discriminators.0.net.4.weight_g', 'discriminator.discriminators.0.net.4.weight_v', 'discriminator.discriminators.0.net.6.weight_g', 'discriminator.discriminators.0.net.6.weight_v', 'discriminator.discriminators.0.net.8.weight_g', 'discriminator.discriminators.0.net.8.weight_v', 'discriminator.discriminators.0.net.10.weight_g', 'discriminator.discriminators.0.net.10.weight_v', 'discriminator.discriminators.0.net.12.weight_g', 'discriminator.discriminators.0.net.12.weight_v', 'discriminator.discriminators.1.net.0.weight_g', 'discriminator.discriminators.1.net.0.weight_v', 'discriminator.discriminators.1.net.2.weight_g', 'discriminator.discriminators.1.net.2.weight_v', 'discriminator.discriminators.1.net.4.weight_g', 'discriminator.discriminators.1.net.4.weight_v', 'discriminator.discriminators.1.net.6.weight_g', 'discriminator.discriminators.1.net.6.weight_v', 'discriminator.discriminators.1.net.8.weight_g', 'discriminator.discriminators.1.net.8.weight_v', 'discriminator.discriminators.1.net.10.weight_g', 'discriminator.discriminators.1.net.10.weight_v', 'discriminator.discriminators.1.net.12.weight_g', 'discriminator.discriminators.1.net.12.weight_v', 'discriminator.discriminators.2.net.0.weight_g', 'discriminator.discriminators.2.net.0.weight_v', 'discriminator.discriminators.2.net.2.weight_g', 'discriminator.discriminators.2.net.2.weight_v', 'discriminator.discriminators.2.net.4.weight_g', 'discriminator.discriminators.2.net.4.weight_v', 'discriminator.discriminators.2.net.6.weight_g', 'discriminator.discriminators.2.net.6.weight_v', 'discriminator.discriminators.2.net.8.weight_g', 'discriminator.discriminators.2.net.8.weight_v', 'discriminator.discriminators.2.net.10.weight_g', 'discriminator.discriminators.2.net.10.weight_v', 'discriminator.discriminators.2.net.12.weight_g', 'discriminator.discriminators.2.net.12.weight_v']
  rank_zero_warn(
/home/jon/miniconda3/envs/ancestor_TTS0.6.2_RV1.0_HF4.18/lib/python3.9/site-packages/pytorch_lightning/core/saving.py:217: UserWarning: Found keys that are not in the model state dict but in the checkpoint: ['discriminator.discriminators.0.net.0.weight', 'discriminator.discriminators.0.net.2.weight', 'discriminator.discriminators.0.net.4.weight', 'discriminator.discriminators.0.net.6.weight', 'discriminator.discriminators.0.net.8.weight', 'discriminator.discriminators.0.net.10.weight', 'discriminator.discriminators.0.net.12.weight', 'discriminator.discriminators.1.net.0.weight', 'discriminator.discriminators.1.net.2.weight', 'discriminator.discriminators.1.net.4.weight', 'discriminator.discriminators.1.net.6.weight', 'discriminator.discriminators.1.net.8.weight', 'discriminator.discriminators.1.net.10.weight', 'discriminator.discriminators.1.net.12.weight', 'discriminator.discriminators.2.net.0.weight', 'discriminator.discriminators.2.net.2.weight', 'discriminator.discriminators.2.net.4.weight', 'discriminator.discriminators.2.net.6.weight', 'discriminator.discriminators.2.net.8.weight', 'discriminator.discriminators.2.net.10.weight', 'discriminator.discriminators.2.net.12.weight']
  rank_zero_warn(
```
