### ISSUE TITLE
stacking in  export_rave.py

### ISSUE THREAD

**Issue by fyam** [acids-ircam/RAVE#40]
Thanks for publishing this interesting project.
I'm trying to make it by following the instruction, but it stacking in here during various trials.
It's helpful if I could have some advises to solve it.
Thank you 

C:\Users\smdlo\Documents\RAVE_nn\RAVE>py export_rave.py --run runs\a01\rave --cached false --name a01
[312.63] exporting model
[1569.23] loading model from checkpoint
[1570.20] using None
Traceback (most recent call last):
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 309, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\smdlo\Documents\RAVE_nn\RAVE\export_rave.py", line 204, in <module>
    model = RAVE.load_from_checkpoint(RUN, strict=False).eval()
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\core\saving.py", line 131, in load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\utilities\cloud_io.py", line 28, in load
    return torch.load(path_or_url, map_location=map_location)
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 236, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 221, in __init__
    _check_seekable(buffer)
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 312, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "C:\Users\smdlo\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 305, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

**Comment by caillonantoine** [comment]
It looks like the last version of the run you are trying to export is empty (check the checkpoint folder). You can fix this error by deleting empty versions from the run folder
