### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' 

### ISSUE THREAD

**Issue by eyesack** [acids-ircam/RAVE#43]
Hi, getting the following error when running train_rave.py. Any ideas?

```
Traceback (most recent call last):
  File "/Users/eyesack/Documents/RAVE/train_rave.py", line 4, in <module>
    from rave.model import RAVE
  File "/Users/eyesack/Documents/RAVE/rave/__init__.py", line 1, in <module>
    from .model import RAVE
  File "/Users/eyesack/Documents/RAVE/rave/model.py", line 5, in <module>
    import pytorch_lightning as pl
  File "/Users/eyesack/anaconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/Users/eyesack/anaconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/Users/eyesack/anaconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/Users/eyesack/anaconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/Users/eyesack/anaconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/Users/eyesack/anaconda3/envs/py39/lib/python3.9/site-packages/torchmetrics/utilities/data.py)
```

**Comment by caillonantoine** [comment]
This comes from the `torchmetrics` package which is apparently broken. I'm working on it !

**Comment by caillonantoine** [comment]
This should be fixed ! Simply re-install your dependencies (`pip install -r requirements.txt`) and it should be ok :)

**Comment by eyesack** [comment]
Huh, now I'm getting this, using the command suggested by cli_helper.py? Wasn't getting this before.

(py39) eyesack@Isaacs-MBP RAVE % python train_rave.py --name stephanie1 --wav /Users/eyesack/Documents/RAVE/StephanieLampreaAudio  --preprocessed /Users/eyesack/Documents/RAVE/temp /stephanie1/rave --sr 44100
usage: train_rave.py [-h] [--data-size DATA_SIZE] [--capacity CAPACITY]
                     [--latent-size LATENT_SIZE] [--ratios RATIOS]
                     [--bias {true,false}] [--no-latency {true,false}]
                     [--min-kl MIN_KL] [--max-kl MAX_KL]
                     [--cropped-latent-size CROPPED_LATENT_SIZE]
                     [--feature-match {true,false}] [--loud-stride LOUD_STRIDE]
                     [--use-noise {true,false}] [--noise-ratios NOISE_RATIOS]
                     [--noise-bands NOISE_BANDS] [--d-capacity D_CAPACITY]
                     [--d-multiplier D_MULTIPLIER] [--d-n-layers D_N_LAYERS]
                     [--warmup WARMUP] [--mode MODE] [--ckpt CKPT]
                     [--preprocessed PREPROCESSED] [--wav WAV] [--sr SR]
                     [--n-signal N_SIGNAL] [--max-steps MAX_STEPS] [--batch BATCH]
                     [--name NAME]
train_rave.py: error: unrecognized arguments: /stephanie1/rave

**Comment by eyesack** [comment]
Never mind, just removed " /stephanie1/rave" and it seems to be working now.
