### ISSUE TITLE
Problem resuming training

### ISSUE THREAD

**Issue by wwerk** [acids-ircam/RAVE#65]
Hi, I am currently trying to resume training from a checkpoint I have been recently training on a SLURM node.
When I try to import the checkpoint I get the following error:

```0: Multiprocessing is handled by SLURM.
0: GPU available: True, used: True
0: TPU available: False, using: 0 TPU cores
0: IPU available: False, using: 0 IPUs
0: HPU available: False, using: 0 HPUs
0: Restoring states from the checkpoint path at runs/llew/rave/version_0/checkpoints/last.ckpt
0: Traceback (most recent call last):
0:   File "/home/training_scripts/../RAVE/train_rave.py", line 166, in <module>
0:     trainer.fit(model, train, val, ckpt_path=run)
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
0:     self._call_and_handle_interrupt(
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
0:     return trainer_fn(*args, **kwargs)
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
0:     results = self._run(model, ckpt_path=self.ckpt_path)
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run
0:     self._restore_modules_and_callbacks(ckpt_path)
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1139, in _restore_modules_and_callbacks
0:     self._checkpoint_connector.restore_model()
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 179, in restore_model
0:     self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 319, in load_model_state_dict
0:     self.lightning_module.load_state_dict(checkpoint["state_dict"])
0:   File "/home/.conda/envs/ravenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
0:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
0: RuntimeError: Error(s) in loading state_dict for RAVE:
0: 	Missing key(s) in state_dict: "saved_step". 
srun: error: lara: task 0: Exited with exit code 1
```

I have checked the previous log and it would seem that the job had gone out of memory when it tried to start switching to the second phase of training.
Is there any way in which such a checkpoint could be recovered?
I presume I could possibly push it into phase two with a lower batch size.

**Comment by caillonantoine** [comment]
You should revert the repo to e26bdfdd4df6b9aafd5b5b07da802e0725f2e946 as a _savedstep_ buffer has been added to the model to account for a bug in pytorch lightning !

**Comment by wwerk** [comment]
> You should revert the repo to [e26bdfd](https://github.com/acids-ircam/RAVE/commit/e26bdfdd4df6b9aafd5b5b07da802e0725f2e946) as a _savedstep_ buffer has been added to the model to account for a bug in pytorch lightning !

Reverting to [e26bdfd](https://github.com/acids-ircam/RAVE/commit/e26bdfdd4df6b9aafd5b5b07da802e0725f2e946) resulted in the same error, so I reverted to the previous [9455a79](https://github.com/acids-ircam/RAVE/commit/9455a79d1924001655adff01748e77e4647196d3). 

With that particular model, the training seems to resume, though it logs negative training speed, which starting from -200it/s goes up to zero, then the process finishes with no errors.

With a different one, I am getting another error when I try to resume from its last checkpoint:
```0: Multiprocessing is handled by SLURM.
0: /home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:51: LightningDeprecationWarning: Setting `Trainer(resume_from_checkpoint=)` is deprecated in v1.5 and will be removed in v1.7. Please pass `Trainer.fit(ckpt_path=)` directly instead.
0:   rank_zero_deprecation(
0: GPU available: True, used: True
0: TPU available: False, using: 0 TPU cores
0: IPU available: False, using: 0 IPUs
0: HPU available: False, using: 0 HPUs
0: /home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:805: LightningDeprecationWarning: `trainer.resume_from_checkpoint` is deprecated in v1.5 and will be removed in v2.0. Specify the fit checkpoint path with `trainer.fit(ckpt_path=)` instead.
0:   ckpt_path = ckpt_path or self.resume_from_checkpoint
0: Restoring states from the checkpoint path at runs/energy/rave/version_1/checkpoints/last.ckpt
0: Traceback (most recent call last):
0:   File "/home/training_scripts/../RAVE/train_rave.py", line 160, in <module>
0:     trainer.fit(model, train, val)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
0:     self._call_and_handle_interrupt(
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
0:     return trainer_fn(*args, **kwargs)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
0:     results = self._run(model, ckpt_path=self.ckpt_path)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run
0:     self._restore_modules_and_callbacks(ckpt_path)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1139, in _restore_modules_and_callbacks
0:     self._checkpoint_connector.restore_model()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 179, in restore_model
0:     self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 319, in load_model_state_dict
0:     self.lightning_module.load_state_dict(checkpoint["state_dict"])
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
0:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
0: RuntimeError: Error(s) in loading state_dict for RAVE:
0: 	Unexpected key(s) in state_dict: "decoder.net.2.net.0.aligned.paddings.0.pad", "decoder.net.2.net.0.aligned.paddings.1.pad", "decoder.net.2.net.1.aligned.paddings.0.pad", "decoder.net.2.net.1.aligned.paddings.1.pad", "decoder.net.2.net.2.aligned.paddings.0.pad", "decoder.net.2.net.2.aligned.paddings.1.pad", "decoder.net.4.net.0.aligned.paddings.0.pad", "decoder.net.4.net.0.aligned.paddings.1.pad", "decoder.net.4.net.1.aligned.paddings.0.pad", "decoder.net.4.net.1.aligned.paddings.1.pad", "decoder.net.4.net.2.aligned.paddings.0.pad", "decoder.net.4.net.2.aligned.paddings.1.pad", "decoder.net.6.net.0.aligned.paddings.0.pad", "decoder.net.6.net.0.aligned.paddings.1.pad", "decoder.net.6.net.1.aligned.paddings.0.pad", "decoder.net.6.net.1.aligned.paddings.1.pad", "decoder.net.6.net.2.aligned.paddings.0.pad", "decoder.net.6.net.2.aligned.paddings.1.pad", "decoder.net.8.net.0.aligned.paddings.0.pad", "decoder.net.8.net.0.aligned.paddings.1.pad", "decoder.net.8.net.1.aligned.paddings.0.pad", "decoder.net.8.net.1.ali
0: gned.paddings.1.pad", "decoder.net.8.net.2.aligned.paddings.0.pad", "decoder.net.8.net.2.aligned.paddings.1.pad", "decoder.net.10.net.0.aligned.paddings.0.pad", "decoder.net.10.net.0.aligned.paddings.1.pad", "decoder.net.10.net.1.aligned.paddings.0.pad", "decoder.net.10.net.1.aligned.paddings.1.pad", "decoder.net.10.net.2.aligned.paddings.0.pad", "decoder.net.10.net.2.aligned.paddings.1.pad", "decoder.synth.paddings.0.pad", "decoder.synth.paddings.1.pad", "decoder.synth.paddings.2.pad". 
srun: error: lara: task 0: Exited with exit code 1

```

**Comment by caillonantoine** [comment]
The negative log comes from pytorch lightning, I am waiting for them to fix the issue. 
For the second issue you can convert your old checkpoints using this https://gist.github.com/caillonantoine/b392f764e691ca445a60d9f84f7f426c

**Comment by wwerk** [comment]
Resuming from a converted checkpoint results in the following:
```0: Multiprocessing is handled by SLURM.
0: /home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:51: LightningDeprecationWarning: Setting `Trainer(resume_from_checkpoint=)` is deprecated in v1.5 and will be removed in v1.7. Please pass `Trainer.fit(ckpt_path=)` directly instead.
0:   rank_zero_deprecation(
0: GPU available: True, used: True
0: TPU available: False, using: 0 TPU cores
0: IPU available: False, using: 0 IPUs
0: HPU available: False, using: 0 HPUs
0: /home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:805: LightningDeprecationWarning: `trainer.resume_from_checkpoint` is deprecated in v1.5 and will be removed in v2.0. Specify the fit checkpoint path with `trainer.fit(ckpt_path=)` instead.
0:   ckpt_path = ckpt_path or self.resume_from_checkpoint
0: Restoring states from the checkpoint path at runs/energy/rave/version_1/checkpoints/converted.ckpt
0: /home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:342: UserWarning: The dirpath has changed from 'runs/energy/rave/version_1/checkpoints' to 'runs/energy/rave/version_2/checkpoints', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.
0:   warnings.warn(
0: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
0: 
0:   | Name          | Type                | Params
0: ------------------------------------------------------
0: 0 | pqmf          | CachedPQMF          | 16.7 K
0: 1 | loudness      | Loudness            | 0     
0: 2 | encoder       | Encoder             | 15.5 M
0: 3 | decoder       | Generator           | 48.7 M
0: 4 | discriminator | StackDiscriminators | 16.9 M
0: ------------------------------------------------------
0: 81.1 M    Trainable params
0: 0         Non-trainable params
0: 81.1 M    Total params
0: 324.381   Total estimated model params size (MB)
0: 2022-06-02 18:35:32.772510: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
0: Restored all states from the checkpoint file at runs/energy/rave/version_1/checkpoints/converted.ckpt
0: SLURM auto-requeueing enabled. Setting signal handlers.
0: /home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py:135: UserWarning: You're resuming from a checkpoint that ended before the epoch ended. This can cause unreliable results if further training is done. Consider using an end-of-epoch checkpoint or enabling fault-tolerant training: https://pytorch-lightning.readthedocs.io/en/stable/advanced/fault_tolerant_training.html
0:   rank_zero_warn(
0: 
Training: 10000it [00:00, ?it/s]
Epoch 86:  41%|████▏     | 10000/24127 [00:00<?, ?it/s]
0: Traceback (most recent call last):
0:   File "/home/training_scripts/../RAVE/train_rave.py", line 160, in <module>
0:     trainer.fit(model, train, val)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
0:     self._call_and_handle_interrupt(
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
0:     return trainer_fn(*args, **kwargs)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
0:     results = self._run(model, ckpt_path=self.ckpt_path)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
0:     results = self._run_stage()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
0:     return self._run_train()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train
0:     self.fit_loop.run()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
0:     self.advance(*args, **kwargs)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
0:     self._outputs = self.epoch_loop.run(self._data_fetcher)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 205, in run
0:     self.on_advance_end()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 255, in on_advance_end
0:     self._run_validation()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 309, in _run_validation
0:     self.val_loop.run()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 211, in run
0:     output = self.on_run_end()
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 187, in on_run_end
0:     self._evaluation_epoch_end(self._outputs)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 309, in _evaluation_epoch_end
0:     self.trainer._call_lightning_module_hook("validation_epoch_end", output_or_outputs)
0:   File "/home/.conda/envs/ravenew/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1593, in _call_lightning_module_hook
0:     output = fn(*args, **kwargs)
0:   File "/home/RAVE/rave/model.py", line 705, in validation_epoch_end
0:     audio, z = list(zip(*out))
0: ValueError: not enough values to unpack (expected 2, got 0)
0: 
Validation: 0it [00:00, ?it/s][A
srun: error: lara: task 0: Exited with exit code 1
```
