### ISSUE TITLE
export rave and train prior errors

### ISSUE THREAD

**Issue by deccolquitt** [acids-ircam/RAVE#66]
seem to be linked.. for one of the models I have been training with the same version of the repo for a few days...

export rave error:

```
[491.94] exporting model
[3091.86] loading model from checkpoint
[3093.63] using /content/drive/MyDrive/RAVE/runs/baisline_3/rave/version_3/checkpoints/last-v1.ckpt
[5213.25] Created a temporary directory at /tmp/tmp2r4ccw1o
[5213.57] Writing /tmp/tmp2r4ccw1o/_remote_module_non_sriptable.py
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/saving.py:218: UserWarning: Found keys that are not in the model state dict but in the checkpoint: ['decoder.net.2.net.0.aligned.paddings.0.pad', 'decoder.net.2.net.0.aligned.paddings.1.pad', 'decoder.net.2.net.1.aligned.paddings.0.pad', 'decoder.net.2.net.1.aligned.paddings.1.pad', 'decoder.net.2.net.2.aligned.paddings.0.pad', 'decoder.net.2.net.2.aligned.paddings.1.pad', 'decoder.net.4.net.0.aligned.paddings.0.pad', 'decoder.net.4.net.0.aligned.paddings.1.pad', 'decoder.net.4.net.1.aligned.paddings.0.pad', 'decoder.net.4.net.1.aligned.paddings.1.pad', 'decoder.net.4.net.2.aligned.paddings.0.pad', 'decoder.net.4.net.2.aligned.paddings.1.pad', 'decoder.net.6.net.0.aligned.paddings.0.pad', 'decoder.net.6.net.0.aligned.paddings.1.pad', 'decoder.net.6.net.1.aligned.paddings.0.pad', 'decoder.net.6.net.1.aligned.paddings.1.pad', 'decoder.net.6.net.2.aligned.paddings.0.pad', 'decoder.net.6.net.2.aligned.paddings.1.pad', 'decoder.net.8.net.0.aligned.paddings.0.pad', 'decoder.net.8.net.0.aligned.paddings.1.pad', 'decoder.net.8.net.1.aligned.paddings.0.pad', 'decoder.net.8.net.1.aligned.paddings.1.pad', 'decoder.net.8.net.2.aligned.paddings.0.pad', 'decoder.net.8.net.2.aligned.paddings.1.pad', 'decoder.synth.paddings.0.pad', 'decoder.synth.paddings.1.pad', 'decoder.synth.paddings.2.pad']
  f"Found keys that are not in the model state dict but in the checkpoint: {keys.unexpected_keys}"
[5720.72] flattening weights
[5807.67] warmup forward pass
[5893.11] build resampling model
[5893.38] script model
[6582.57] save rave_baisline_3_V3.ts
```

train prior error (w/ generated ts file)

```
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Traceback (most recent call last):
  File "train_prior.py", line 117, in <module>
    resume_from_checkpoint=search_for_run(args.CKPT),
  File "/content/drive/MyDrive/RAVE/rave/core.py", line 180, in search_for_run
    run_path = list(filter(lambda e: "last" in e, run_path))[-1]
IndexError: list index out of range
```

thanks in advance, have just continued training the model at the first stage for the time being

**Comment by caillonantoine** [comment]
For the rave export it is not an error but a warning that you should ignore.

You have no checkpoints in your run folder,  that is why the prior model can't _resume_ anything.
