### ISSUE TITLE
Profocol buffers error TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by jreus** [acids-ircam/RAVE#86]
After a fresh install of miniconda and updating conda itself (Linux, Ubuntu) I'm getting the following error when trying to train a RAVE model.

Prepending `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` to the training command gets it running. But is this expected behavior? Seems to be some kind of compatibility issue with the latest version of python...?

```
$ CUDA_VISIBLE_DEVICES=1 python train_rave.py --name blonk_nolatency_1 --wav ~/datasets/unconditional/Blonk/Vocalor/ --preprocessed ../jobs/rave/blonk_nolatency_1/tmp --sr 48000 --data-size 16 --no-latency true                                     

Traceback (most recent call last):
  File "/its/home/user/RAVE/train_rave.py", line 4, in <module>
    from rave.model import RAVE
  File "/its/home/user/RAVE/rave/__init__.py", line 1, in <module>
    from .model import RAVE
  File "/its/home/user/RAVE/rave/model.py", line 5, in <module>
    import pytorch_lightning as pl
  File "/its/home/user/.local/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/its/home/user/.local/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/its/home/user/.local/lib/python3.9/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/its/home/user/.local/lib/python3.9/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/its/home/user/.local/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 40, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
  File "/its/home/user/.local/lib/python3.9/site-packages/pytorch_lightning/loggers/__init__.py", line 18, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/its/home/user/.local/lib/python3.9/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/its/home/user/.local/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/its/home/user/.local/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/its/home/user/.local/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/its/home/user/.local/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/its/home/user/.local/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/its/home/user/.local/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/its/home/user/.local/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/its/home/user/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

**Comment by caillonantoine** [comment]
what's your python version ?

**Comment by jreus** [comment]
> what's your python version ?
Python 3.9.12

**Comment by wwerk** [comment]
I am getting the same error using the Colab notebook.

**Comment by caillonantoine** [comment]
Pull the latest version of rave and update the requirements (`pip install -r requirements.txt`) ! It should work :) the colab has also been updated to reflect this change !

**Comment by jreus** [comment]
Awesome! Thanks Antoine :-) ...that fixed it for me
> Pull the latest version of rave and update the requirements (`pip install -r requirements.txt`) ! It should work :) the colab has also been updated to reflect this change !

**Comment by jreus** [comment]
Awesome! Thanks Antoine :-) ...that fixed it for me
> Pull the latest version of rave and update the requirements (`pip install -r requirements.txt`) ! It should work :) the colab has also been updated to reflect this change !
